name: pooch
channels:
    - conda-forge
    - defaults
dependencies:
    - python==3.8
    - pip
    - requests
    - packaging
    - appdirs
    # Development requirements
    - setuptools_scm
    - pytest
    - pytest-cov
    - pytest-localftpserver
    - pathspec
    - coverage
    - black>=20.8b1
    - flake8
    - pylint==2.4.*
    - sphinx==3.5.*
    - sphinx-book-theme==0.0.41
