name: pooch
channels:
    - conda-forge
    - defaults
dependencies:
    - python==3.7
    - pip
    - requests
    - packaging
    - appdirs
    # Development requirements
    - setuptools_scm
    - pytest
    - pytest-cov
    - pytest-localftpserver
    - coverage
    - black>=20.8b1
    - flake8
    - pylint==2.4.*
    - sphinx==3.3.*
    - sphinx_rtd_theme==0.5.0
    - pathspec
