name: pooch
channels:
    - conda-forge
    - defaults
dependencies:
    - python==3.10
    - pip
    # Run
    - requests
    - packaging
    - appdirs
    # Build
    - build
    # Test
    - pytest
    - pytest-cov
    - pytest-localftpserver
    - coverage
    # Documentation
    - sphinx==3.5.*
    - sphinx-book-theme==0.0.41
    - sphinx-panels==0.5.*
    # Style
    - pathspec
    - black>=20.8b1
    - flake8
    - pip:
      - pylint==2.4.*
